#!/usr/bin/env python3
"""
scan_components.py — 扫描项目组件库，输出 component-inventory.md 的初稿。

用法:
    python scan_components.py <repo_root> [--roots src/components packages/ui/src] [--mode full-scan|on-demand]

行为:
- 递归查找 .tsx / .ts / .jsx / .vue 文件
- 用正则提取 export 的组件名（默认导出 + 命名导出）
- 提取 props 接口（TS interface / type）字段名
- 输出到 stdout 或追加到 <repo_root>/.comate/component-inventory.md

注意：这是粗扫描，给后续匹配作起点；视觉特征字段需要后续人工或视觉模型补充。
"""
import argparse
import os
import re
import sys
from datetime import date
from pathlib import Path

EXPORT_RE = re.compile(
    r"export\s+(?:default\s+)?(?:function|const|class)\s+([A-Z][A-Za-z0-9_]*)"
)
NAMED_EXPORT_RE = re.compile(r"export\s*\{\s*([^}]+)\s*\}")
PROPS_INTERFACE_RE = re.compile(
    r"(?:interface|type)\s+([A-Z][A-Za-z0-9_]*Props)\s*=?\s*\{([^}]*)\}",
    re.DOTALL,
)
PROP_FIELD_RE = re.compile(r"^\s*([a-zA-Z_][a-zA-Z0-9_]*)\??\s*:", re.MULTILINE)

SUPPORTED_EXTS = {".tsx", ".ts", ".jsx", ".js", ".vue"}
DEFAULT_ROOTS = ["src/components", "packages/ui/src", "src/ui", "components"]


def find_component_files(repo_root: Path, roots: list[str]) -> list[Path]:
    files = []
    for r in roots:
        base = repo_root / r
        if not base.exists():
            continue
        for p in base.rglob("*"):
            if p.suffix in SUPPORTED_EXTS and not any(
                seg in {"__tests__", "node_modules", "dist", "build"} for seg in p.parts
            ):
                files.append(p)
    return files


def extract_components(file_path: Path) -> list[dict]:
    try:
        text = file_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return []

    names = set(EXPORT_RE.findall(text))
    for m in NAMED_EXPORT_RE.findall(text):
        for token in m.split(","):
            token = token.strip().split(" as ")[0].strip()
            if token and token[0].isupper():
                names.add(token)

    props_map = {}
    for pm in PROPS_INTERFACE_RE.finditer(text):
        iface_name = pm.group(1)
        body = pm.group(2)
        fields = PROP_FIELD_RE.findall(body)
        comp_name = iface_name.replace("Props", "")
        if comp_name:
            props_map[comp_name] = fields

    out = []
    for name in sorted(names):
        out.append(
            {
                "name": name,
                "path": str(file_path),
                "props": props_map.get(name, []),
            }
        )
    return out


def render_markdown(repo_root: Path, components: list[dict], mode: str, roots: list[str]) -> str:
    lines = [
        "---",
        f"mode: {mode}",
        f"last_scan: {date.today().isoformat()}",
        "scan_roots:",
    ]
    for r in roots:
        lines.append(f"  - {r}")
    lines.append("---")
    lines.append("")
    lines.append("# Component Inventory")
    lines.append("")
    lines.append(f"Auto-generated by `scan_components.py`. Total: {len(components)} components.")
    lines.append("")

    by_name = {}
    for c in components:
        by_name.setdefault(c["name"], []).append(c)

    for name in sorted(by_name):
        entries = by_name[name]
        primary = entries[0]
        rel_path = os.path.relpath(primary["path"], repo_root)
        lines.append(f"## {name}")
        lines.append(f"- path: `{rel_path}`")
        if primary["props"]:
            lines.append(f"- key_props: {{ {', '.join(primary['props'][:12])} }}")
        if len(entries) > 1:
            lines.append(f"- duplicates_at: {[os.path.relpath(e['path'], repo_root) for e in entries[1:]]}")
        lines.append("- variants: TBD")
        lines.append("- visual_signature: TBD")
        lines.append("- semantic_tags: [TBD]")
        lines.append(f"- last_seen: {date.today().isoformat()}")
        lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("repo_root", type=Path)
    ap.add_argument("--roots", nargs="*", default=None)
    ap.add_argument("--mode", choices=["full-scan", "on-demand"], default="full-scan")
    ap.add_argument("--out", type=Path, default=None, help="默认写入 <repo_root>/.comate/component-inventory.md")
    args = ap.parse_args()

    repo_root: Path = args.repo_root.resolve()
    if not repo_root.is_dir():
        print(f"repo_root not a directory: {repo_root}", file=sys.stderr)
        sys.exit(1)

    roots = args.roots or [r for r in DEFAULT_ROOTS if (repo_root / r).exists()]
    if not roots:
        print("no scan root found; please pass --roots", file=sys.stderr)
        sys.exit(2)

    files = find_component_files(repo_root, roots)
    components = []
    for f in files:
        components.extend(extract_components(f))

    md = render_markdown(repo_root, components, args.mode, roots)

    out = args.out or (repo_root / ".comate" / "component-inventory.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")
    print(f"wrote {out} ({len(components)} components from {len(files)} files)")


if __name__ == "__main__":
    main()
